CURRENT_GPU: 0
DATASET:
    NAME: "gdal_landcover_common"
    ROOT_PATH: /data/open_datasets/rsipac #/data/datasets/GID_RGB_15_1024x1024 #J:\Expert_Datasets\GreenLand_3band_512x512_2numclass
    MEAN: [0.2929289, 0.26457465, 0.20767461] # [0.3539229, 0.3734769, 0.34095916]  #  [0.5, 0.5, 0.5]
    STD:  [0.09196425, 0.09383065, 0.10830729] # [0.23289922, 0.22774169, 0.22549641] #     #[0.5, 0.5, 0.5]
    NUM_CHANNELS: 3
    NUM_CLASSES: 6
    CLASS_INDEX: [{1: 0, 2: 1, 3: 2, 4: 3, 5: 4, 6: 5}]   #[0, 255]
    IGNORE_INDEX: -1
TRAIN:
    EPOCHS: 200
    CROP_SIZE: 512 #(512, 512)
    BATCH_SIZE: 12
    DATA_LIST: #/data/open_datasets/GID_RGB_15_512x512_0overlap_sub/train/GID15_train_list_subset_balance.txt
    BACKBONE_PRETRAINED_PATH: /code/python/pytorch/pytorchAI_segmentation_GID/pretrain_pth/efficientnet-b3-5fb5a3c3.pth #/data/code/pytorchAI_segmentation/pretrain_pth/efficientnet-b3-5fb5a3c3.pth #/data/code/pytorchAI_segmentation/pretrain_pth/efficientnet-b3-5fb5a3c3.pth
    PRETRAINED_MODEL_PATH: #/code/python/pytorch/runs/checkpoints/Unet_efficientnet-b3_gdal_landcover_2021-07-12-13-52/best_checkpoint.pth.tar
    LOG_SAVE_DIR: /dataset/rsipac_runs/logs
    MODEL_SAVE_DIR: /dataset/rsipac_runs/checkpoints
    AMP: True
VAL:
    BATCH_SIZE: 12
    CROP_SIZE: 512 #512 #(512, 512)
    DATA_LIST: #/data/open_datasets/GID_RGB_15_512x512_0overlap_sub/train/GID15_train_list_subset_balance.txt
TEST:
    BATCH_SIZE: 12
    #CROP_SIZE: 512 #512 #(512, 512)
    TEST_MODEL_PATH: #/data_zs/code/checkpoints/Unet_efficientnet-b3_gdal_landcover_2021-07-12-13-52/best_checkpoint.pth.tar #../trained_models/hrnet_w18_small_v1_cityscapes_cls19_1024x2048_trainset_segmentron.pth

SOLVER:
    OPTIMIZER: "sgd"
    LR_SCHEDULER: poly #cosine
    LR: 0.005
    LOSS_NAME: ce_loss #imagebase_CEloss #focal_diceloss #"pixelcontrast"
MODEL:
    SOURCE: "smp"
    MODEL_NAME: "Unet"
    BACKBONE: "efficientnet-b3"
    ACTIVATION: #"sigmoid"

VISUAL:
    LOG_SAVE_DIR: /dataset/output/sandong_runs/logs #/dataset/output/sandong_runs/logs #/data_zs/output/sandong_runs/logs #/code/python/pytorch/runs/logs
    MODEL_SAVE_DIR: /dataset/output/sandong_runs/checkpoint #/dataset/output/sandong_runs/checkpoint #/data_zs/output/sandong_runs/checkpoint #/code/python/pytorch/runs/checkpoints
    OUTPUT_DIR: /dataset/output/sandong_runs/visual #/dataset/output/sandong_runs/visual #/data_zs/output/sandong_runs/visual
    CURRENT_NAME: sandong_segformer_b3_ce_focal_fold0-515_0123_scale2_ep200

UTILS:
    VAL_START: 0 #62 #62
    EPOCH_STOP: 200 #66 #67



