CURRENT_GPU: 0
DATASET:
    NAME: "gdal_binary"
    ROOT_PATH: #/data/open_datasets/GID_RGB_15_512x512_0overlap_sub #/data/datasets/GID_RGB_15_1024x1024 #J:\Expert_Datasets\GreenLand_3band_512x512_2numclass
    DATA_LIST: /dataset/config/config-f4d75a7a04b146e4808cc743ebf37f31_water.json #/data/open_datasets/GID_RGB_15_512x512_0overlap_sub/train/GID15_train_list_subset_balance.txt
    MEAN: [0.13870567, 0.13235442, 0.12146049, 0.2531407, 0.17776759, 0.12983494] #[0.5, 0.5, 0.5, 0.5, 0.5, 0.5] # [0.3539229, 0.3734769, 0.34095916]  #  [0.5, 0.5, 0.5]
    STD:  [0.06697738, 0.065091915, 0.06634818, 0.11326719, 0.08240963, 0.06558757] #[0.5, 0.5, 0.5, 0.5, 0.5, 0.5] # [0.23289922, 0.22774169, 0.22549641] #     #[0.5, 0.5, 0.5]
    NUM_CHANNELS: 6
    NUM_CLASSES: 1
    CLASS_INDEX: [60]   #[0, 255]
    IGNORE_INDEX: -1
TRAIN:
    EPOCHS: 100
    CROP_SIZE: 1024 #(512, 512)
    BATCH_SIZE: 6
    BACKBONE_PRETRAINED_PATH: /dataset/code/pytorchAI_segmentation_landcover_transfer/pretrain_pth/efficientnet-b3-5fb5a3c3.pth #/data/code/pytorchAI_segmentation/pretrain_pth/efficientnet-b3-5fb5a3c3.pth #/data/code/pytorchAI_segmentation/pretrain_pth/efficientnet-b3-5fb5a3c3.pth
    PRETRAINED_MODEL_PATH: #/code/python/pytorch/runs/checkpoints/Unet_efficientnet-b3_gdal_landcover_2021-07-12-13-52/best_checkpoint.pth.tar
    LOG_SAVE_DIR: /dataset/code/runs/logs
    MODEL_SAVE_DIR: /dataset/code/runs/checkpoints
TEST:
    BATCH_SIZE: 6
    CROP_SIZE: #512 #(512, 512)
    TEST_MODEL_PATH: #/data/data_zs/code/pytorchAI_segmentation_landcover30/runs/checkpoints/Unet_efficientnet-b3_gdal_landcover_2021-08-19-13-50/best_checkpoint.pth.tar #../trained_models/hrnet_w18_small_v1_cityscapes_cls19_1024x2048_trainset_segmentron.pth

SOLVER:
    OPTIMIZER: "adam" #"sgd"
    LR: 0.001
    LOSS_NAME: focal_diceloss #imagebase_CEloss #focal_diceloss #"pixelcontrast"
MODEL:
    SOURCE: "smp"
    MODEL_NAME: "Unet"
    BACKBONE: "efficientnet-b3"
    ACTIVATION: "sigmoid"
    THRESHOLD: 0.3
VISUAL:
    OUTPUT_DIR: /dataset/code/runs/visual #../runs/visual/

