CURRENT_GPU: 0
DATASET:
    NAME: "gdal_landcover"  #"gdal_landcover_common"
    ROOT_PATH: /data_zs/data/landcover30_1024x1024_6295 #/data/datasets/GID_RGB_15_1024x1024 #J:\Expert_Datasets\GreenLand_3band_512x512_2numclass
    #DATA_LIST: #/data/open_datasets/GID_RGB_15_512x512_0overlap_sub/train/GID15_train_list_subset_balance.txt
    MEAN: [0.12661575, 0.120581664, 0.11089562, 0.2224456, 0.15773198, 0.11631401] # [0.3539229, 0.3734769, 0.34095916]  #  [0.5, 0.5, 0.5]
    STD:  [0.076352194, 0.07372638, 0.07317314, 0.1314828, 0.09468626, 0.07327465] # [0.23289922, 0.22774169, 0.22549641] #     #[0.5, 0.5, 0.5]
    NUM_CHANNELS: 6
    NUM_CLASSES: 9
    CLASS_INDEX: [0, 10, 20, 30, 40, 50, 60, 80, 255]   #[0, 255]
    IGNORE_INDEX: -1
TRAIN:
    EPOCHS: 200
    CROP_SIZE: 512 #(512, 512)
    BATCH_SIZE: 6
    BACKBONE_PRETRAINED_PATH: /data_zs/data/pretrained_models/mit_b3.pth #/data/code/pytorchAI_segmentation/pretrain_pth/efficientnet-b3-5fb5a3c3.pth #/data/code/pytorchAI_segmentation/pretrain_pth/efficientnet-b3-5fb5a3c3.pth
    PRETRAINED_MODEL_PATH: #/code/python/pytorch/runs/checkpoints/Unet_efficientnet-b3_gdal_landcover_2021-07-12-13-52/best_checkpoint.pth.tar
#    LOG_SAVE_DIR: ../runs/logs
#    MODEL_SAVE_DIR: ../runs/checkpoints
TEST:
    BATCH_SIZE: 1
    CROP_SIZE: #512 #(512, 512)
    TEST_MODEL_PATH: #/data_zs/code/runs/checkpoints/SegFormer_mit_b3_gdal_landcover_2021-09-13-12-25/best_checkpoint.pth.tar #/data_zs/code/checkpoints/Unet_efficientnet-b3_gdal_landcover_2021-07-12-13-52/best_checkpoint.pth.tar #../trained_models/hrnet_w18_small_v1_cityscapes_cls19_1024x2048_trainset_segmentron.pth

SOLVER:
    OPTIMIZER: "poly_adamw"
    LR: 6e-5
    LOSS_NAME: sce_loss #imagebase_CEloss #focal_diceloss #"pixelcontrast"
MODEL:
    SOURCE: #"smp"
    MODEL_NAME: "SegFormer" #"Unet"
    BACKBONE: "mit_b3" #"efficientnet-b3"
    ACTIVATION: #"sigmoid"

