CURRENT_GPU: 1
DATASET:
    NAME: "gdal_landcover"
    ROOT_PATH: /data_zs/data/test_crop #/data/open_datasets/GID_RGB_15_512x512_0overlap_sub #/data/datasets/GID_RGB_15_1024x1024 #J:\Expert_Datasets\GreenLand_3band_512x512_2numclass
    DATA_LIST: #/Radi-server/train/train/ccfc37af645d40389127c7850c7469e8/dataset/config-ccfc37af645d40389127c7850c7469e8_v2.json #/data/open_datasets/GID_RGB_15_512x512_0overlap_sub/train/GID15_train_list_subset_balance.txt
    MEAN: [0.13870567, 0.13235442, 0.12146049, 0.2531407, 0.17776759, 0.12983494] #[0.5, 0.5, 0.5, 0.5, 0.5, 0.5] # [0.3539229, 0.3734769, 0.34095916]  #  [0.5, 0.5, 0.5]
    STD:  [0.06697738, 0.065091915, 0.06634818, 0.11326719, 0.08240963, 0.06558757] #[0.5, 0.5, 0.5, 0.5, 0.5, 0.5] # [0.23289922, 0.22774169, 0.22549641] #     #[0.5, 0.5, 0.5]
    NUM_CHANNELS: 6
    NUM_CLASSES: 8
    CLASS_INDEX: [0, 10, 20, 30, 40, 50, 60, 80]   #[0, 255]
    IGNORE_INDEX: 0
TRAIN:
    EPOCHS: 200
    CROP_SIZE: 1024 #(512, 512)
    BATCH_SIZE: 8
    BACKBONE_PRETRAINED_PATH: /data_zs/code/pytorchAI_segmentation_landcover_transfer/pretrain_pth/efficientnet-b3-5fb5a3c3.pth #/data/code/pytorchAI_segmentation/pretrain_pth/efficientnet-b3-5fb5a3c3.pth #/data/code/pytorchAI_segmentation/pretrain_pth/efficientnet-b3-5fb5a3c3.pth
    PRETRAINED_MODEL_PATH: #/code/python/pytorch/runs/checkpoints/Unet_efficientnet-b3_gdal_landcover_2021-07-12-13-52/best_checkpoint.pth.tar
    LOG_SAVE_DIR: ../runs/logs
    MODEL_SAVE_DIR: ../runs/checkpoints
TEST:
    BATCH_SIZE: 8
    CROP_SIZE: #512 #(512, 512)
    TEST_MODEL_PATH: /data_zs/code/pytorchAI_segmentation_landcover_transfer/runs/checkpoints/Unet_efficientnet-b3_gdal_landcover_2021-08-16-13-45/best_checkpoint.pth.tar #../trained_models/hrnet_w18_small_v1_cityscapes_cls19_1024x2048_trainset_segmentron.pth

SOLVER:
    OPTIMIZER: "sgd"
    LR: 0.005
    LOSS_NAME: sce_loss #imagebase_CEloss #focal_diceloss #"pixelcontrast"
MODEL:
    SOURCE: "smp"
    MODEL_NAME: "Unet"
    BACKBONE: "efficientnet-b3"
    ACTIVATION: #"sigmoid"

