DATASET:
    NAME: "landcover9num"
    ROOT_PATH: /data/Landcover/landcover_3band_512x512_9numclass
    MEAN: [0.32259592, 0.37003833, 0.33403504] #[0.33403504, 0.37003833, 0.32259592]  [0.5, 0.5, 0.5]
    STD: [0.11366305, 0.12238872, 0.14451134] #[0.14451134, 0.12238872, 0.11366305]      #[0.5, 0.5, 0.5]
    NUM_CLASSES: 10
TRAIN:
    BACKBONE_PRETRAINED_PATH: /data/Landcover/pretrain_pth/tf-xception65-270e81cf.pth
    PRETRAINED_MODEL_PATH:
    MODEL_SAVE_DIR: tools/runs/checkpoints/
    LOG_SAVE_DIR: tools/runs/logs
    EPOCHS: 400
    BATCH_SIZE: 4
    CROP_SIZE: 512
TEST:
    BATCH_SIZE: 4
    #CROP_SIZE: (1025, 2049)
    TEST_MODEL_PATH: E:\data\projects_and_topic\LULC_HuangHua\checkpoints\DeepLabV3_Plus_xception65_landcover9num_2021-03-07-09-34\best_checkpoint.pth.tar #E:\data\projects_and_topic\LULC_HuangHua\runs\checkpoints\DeepLabV3_Plus_xception65_landcover9num_2021-02-02-10-37\best_checkpoint.pth.tar #E:\data\projects_and_topic\LULC_HuangHua\runs_new\runs\checkpoints\DeepLabV3_Plus_xception65_landcover9num_2021-03-07-09-34\102_checkpoint.pth.tar #E:\data\projects_and_topic\LULC_HuangHua\runs\checkpoints\DeepLabV3_Plus_xception65_landcover9num_2021-02-02-10-37\best_checkpoint.pth.tar                      #trained_models/deeplabv3_plus_xception_segmentron.pth

SOLVER:
    LR: 0.01

MODEL:
    MODEL_NAME: "DeepLabV3_Plus"
    BACKBONE: "xception65"
    BN_EPS_FOR_ENCODER: 1e-3
