DATASET:
    NAME: "naic"
    MEAN: [0.5, 0.5, 0.5]
    STD: [0.5, 0.5, 0.5]
TRAIN:
    EPOCHS: 400
    BATCH_SIZE: 18
    CROP_SIZE: 256
TEST:
    BATCH_SIZE: 16
    #CROP_SIZE: (1025, 2049)
    TEST_MODEL_PATH: E:\code\python\pytorch\my_code\Multi_models\SegmenTron-master\SegmenTron-master\tools\runs\checkpoints\DeepLabV3_Plus_xception65_naic_2021-01-04-13-47\best_model.pth                      #trained_models/deeplabv3_plus_xception_segmentron.pth

SOLVER:
    LR: 0.02

MODEL:
    MODEL_NAME: "DeepLabV3_Plus"
    BACKBONE: "xception65"
    BN_EPS_FOR_ENCODER: 1e-3
