CURRENT_GPU: 1
TRAIN_STEP_ADD: False
DATASET:
    NAME: "gdal_landcover"
    ROOT_PATH: /data_zs/data/landcover30_1024x1024_6295 #/data/open_datasets/rsipac_semi_20000 #/data/open_datasets/rsipac_semi_full #/data/open_datasets/rsipac_semi_20000  #/data/open_datasets/rsipac_20000 #/data/datasets/GID_RGB_15_1024x1024 #J:\Expert_Datasets\GreenLand_3band_512x512_2numclass
    MEAN: [0.12661575, 0.120581664, 0.11089562, 0.2224456, 0.15773198, 0.11631401] #[0.29310304, 0.2636692, 0.20883968, 0.39742813]  #[0.5, 0.5, 0.5]
    STD:  [0.076352194, 0.07372638, 0.07317314, 0.1314828, 0.09468626, 0.07327465] #[0.09101917, 0.09300123, 0.106814794, 0.1142725]       #[0.5, 0.5, 0.5]
    NUM_CHANNELS: 6 #4
    NUM_CLASSES: 9
    CLASS_INDEX: [0, 10, 20, 30, 40, 50, 60, 80, 255]   #[0, 255]
    IGNORE_INDEX: 250

TRAIN:
    EPOCHS: 200
    CROP_SIZE: 512 #(512, 512)
    BATCH_SIZE: 3
    GRAD_STEPS: 1
    MODEL_SCALE: 1
    DATA_LIST: #/workspace/dataset/rsipac_semi_train_list_21000_b3.txt #/dataset/config/rsipac/select13965_from_rsipac_semi_full_35000_class_balance.txt #/data/open_datasets/rsipac_semi_20000/train/trainRsipac_semi_label.p #/dataset/config/rsipac/select13965_from_rsipac_semi_full_35000_class_balance.txt #/data/open_datasets/rsipac_20000/train/trainRsipac_label.p
    BACKBONE_PRETRAINED_PATH: /data_zs/data/pretrained_models/mit_b3.pth #/data/code/pytorchAI_segmentation/pretrain_pth/efficientnet-b3-5fb5a3c3.pth #/data/code/pytorchAI_segmentation/pretrain_pth/efficientnet-b3-5fb5a3c3.pth
    PRETRAINED_MODEL_PATH:  /data_zs/landcover30_runs/checkpoint/segformer_b3_ce_dice_512/18_0.41742_checkpoint.pth.tar #/workspace/runs/66_0.38098_checkpoint.pth.tar #/workspace/runs/88_0.37473_checkpoint.pth.tar #/dataset/rsipac_runs/semi_stage/checkpoints/SegFormer_mit_b3_gdal_landcover_common_2021-10-25-08-51/best_checkpoint.pth.tar
    AMP: True #True
VAL:
    BATCH_SIZE: 4
    CROP_SIZE: 512 #512 #(512, 512)
    DATA_LIST: #/workspace/dataset/rsipac_semi_val_list_6000_b3.txt #/dataset/config/rsipac/select5985_val_from_rsipac_semi_full_35000_remain_random.txt #/data/open_datasets/GID_RGB_15_512x512_0overlap_sub/train/GID15_train_list_subset_balance.txt
TEST:
    BATCH_SIZE: 6
    CROP_SIZE: #512 #(512, 512)
    TEST_MODEL_PATH: /data_zs/landcover30_runs/checkpoint/segformer_b3_ce_dice_512/best_checkpoint.pth.tar #/workspace/runs/best_checkpoint.pth.tar #/dataset/rsipac_runs/checkpoints/SegFormer_mit_b1_gdal_landcover_common_2021-10-17-13-00/best_checkpoint.pth.tar #/dataset/rsipac_runs/checkpoints/SegFormer_mit_b5_gdal_landcover_common_2021-10-06-08-00/best_checkpoint.pth.tar #/dataset/rsipac_runs/checkpoints/best_0.66343_68.11_checkpoint.pth.tar #/dataset/rsipac_runs/checkpoints/SegFormer_mit_b3_gdal_landcover_common_2021-10-03-14-14/best_checkpoint.pth.tar #/dataset/rsipac_runs/checkpoints/SegFormer_mit_b3_gdal_landcover_common_2021-10-02-11-41/98_0.66089_checkpoint.pth.tar #/dataset/rsipac_runs/checkpoints/SegFormer_mit_b3_gdal_landcover_common_2021-09-28-01-30/59_0.66541_checkpoint.pth.tar #/dataset/rsipac_runs/checkpoints/SegFormer_mit_b3_gdal_landcover_common_2021-09-25-11-32/120_0.66107_checkpoint.pth.tar
    USE_TTA: True

SOLVER:
    OPTIMIZER: "poly_adamw"
    LR_SCHEDULER: poly #cosine
    LR: 6e-5
    LOSS_NAME: ce_focal_diceloss #ohem_ce_loss_v2 #ce_focal_diceloss #ce_focal_diceloss #ce_focalloss #dice_sce_contrast_loss #ce_loss #imagebase_CEloss #focal_diceloss #"pixelcontrast"

MODEL:
    SOURCE: #"smp"
    MODEL_NAME: "SegFormer" #"Unet"
    BACKBONE: "mit_b3" #"efficientnet-b3"
    ACTIVATION: #"sigmoid"

VISUAL:
    LOG_SAVE_DIR: /data_zs/landcover30_runs/logs #/code/python/pytorch/runs/logs
    MODEL_SAVE_DIR: /data_zs/landcover30_runs/checkpoint #/code/python/pytorch/runs/checkpoints
    OUTPUT_DIR: /data_zs/landcover30_runs/visual
    CURRENT_NAME: segformer_b3_ce_dice_512_preudo_label
UTILS:
    VAL_START: 0 #62 #62
    EPOCH_STOP: 200 #66 #67
